---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: jaybrueder/ansible:centos7
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: inspec