---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ghcr.io/infralovers/training-ansible-examples
    dockerfile: Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  env: {}
verifier:
  name: ansible
