---
- name: Verify
  hosts: all
  vars:
    auditor_test_directory: /tmp/molecule/cinc-auditor
    use_cinc_auditor: false
  tasks:
    - name: Create audtior test directory
      ansible.builtin.file:
        path: "{{ auditor_test_directory }}"
        state: directory

    - name: Copy audtior test directories
      ansible.builtin.file:
        path: "{{ auditor_test_directory }}/{{ item.path }}"
        state: directory
        mode: 0755
      with_community.general.filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'directory'

    - name: Copy audtior test files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ auditor_test_directory }}/{{ item.path }}"
        mode: 0644
      with_community.general.filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'file'

    - name: Execute tests
      block:

      - name: Execute cinc auditor
        when: use_cinc_auditor
        register: cinc_test_results
        become: true
        changed_when: false
        ignore_errors: true
        no_log: true
        ansible.builtin.command:
          chdir: "{{ auditor_test_directory }}"
          cmd: "/opt/cinc-auditor/bin/cinc-auditor exec --no-color ."

      - name: Execute mondoo/cnspec
        when: not use_cinc_auditor
        register: mondoo_test_results
        become: true
        changed_when: false
        ignore_errors: true
        no_log: true
        ansible.builtin.command:
          chdir: "{{ auditor_test_directory }}"
          cmd: "cnspec scan local --score-threshold 80 -f test_default.mql"

      - name: test_result
        set_fact:
          test_results: '{{ use_cinc_auditor | ansible.builtin.ternary(cinc_test_results, mondoo_test_results) }}'

    - name: Fail when tests fail
      ansible.builtin.assert:
        that: test_results.rc == 0
        fail_msg: "auditor failed {{ test_results.stdout }}"
        success_msg: "auditor successful"
