---
- name: Verify
  hosts: all
  become: true
  vars:
    auditor_test_directory: /tmp/molecule/cinc-auditor
  tasks:
    - name: Download cinc-auditor
      get_url:
        url: https://omnitruck.cinc.sh/install.sh
        dest: /tmp/install.sh
        mode: '0775'

    - name: Install cinc-auditor
      shell: "bash /tmp/install.sh -s -- -P cinc-auditor -v 4"

    - name: Create audtior test directory
      file:
        path: "{{ auditor_test_directory }}"
        state: directory

    - name: Copy audtior test directories
      file:
        path: "{{ auditor_test_directory }}/{{ item.path }}"
        state: directory
        mode: 0755
      with_filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'directory'

    - name: Copy audtior test files
      copy:
        src: "{{ item.src }}"
        dest: "{{ auditor_test_directory }}/{{ item.path }}"
        mode: 0644
      with_filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'file'

    - name: Execute auditor tests
      command: "/opt/cinc-auditor/bin/cinc-auditor exec {{ auditor_test_directory }}"
      register: test_results
      changed_when: false
      ignore_errors: true

    - name: Display details about the auditor results
      debug:
        msg: "{{ test_results.stdout_lines }}"

    - name: Fail when tests fail
      fail:
        msg: "Auditor failed to validate"
      when: test_results.rc != 0
