---
- name: Verify
  hosts: all
  vars:
    auditor_test_directory: /tmp/molecule/cinc-auditor
  tasks:
    - name: Download cinc-auditor
      ansible.builtin.get_url:
        url: https://omnitruck.cinc.sh/install.sh
        dest: /tmp/install.sh
        mode: '0700'
        owner: root

    - name: Install cinc-auditor
      become: true
      ansible.builtin.shell:
        executable: bash
        cmd: "/tmp/install.sh -P cinc-auditor -v 6"
        creates: /opt/cinc-auditor/bin/cinc-auditor

    - name: Create audtior test directory
      ansible.builtin.file:
        path: "{{ auditor_test_directory }}"
        state: directory

    - name: Copy audtior test directories
      ansible.builtin.file:
        path: "{{ auditor_test_directory }}/{{ item.path }}"
        state: directory
        mode: 0755
      with_community.general.filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'directory'

    - name: Copy audtior test files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ auditor_test_directory }}/{{ item.path }}"
        mode: 0644
      with_community.general.filetree: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/"
      when: item.state == 'file'

    - name: Execute auditor tests
      register: test_results
      become: true
      changed_when: false
      ignore_errors: true
      no_log: true
      ansible.builtin.command:
        chdir: "{{ auditor_test_directory }}"
        cmd: "/opt/cinc-auditor/bin/cinc-auditor exec --no-color ."

    - name: Fail when tests fail
      ansible.builtin.assert:
        that: test_results.rc == 0
        fail_msg: "auditor failed {{ test_results.stdout_lines }}"
        success_msg: "auditor successful"
